name: Demo K8s Workflow

env:
  IMAGE_TAG: ${{ github.run_number }}


on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo
        run: echo ${{ secrets.DOCKERHUB_TOKEN }}