name: Bump version
on:
  pull_request:
    types: [opened, reopened]
    branches: [ test ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'
