name: Notify Slack

env:
  IMAGE_TAG: 8990

on:
  push:
    branches:
      - feature/3
jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          tags: frdevelopergen/react-app-nginx:${{ env.IMAGE_TAG }}
          build-args: |
            PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: frdevelopergen/react-app-nginx:${{ env.IMAGE_TAG }}
      - name: Send message to Slack
        uses: rtCamp/action-slack-notify@v2.2.0
        with:
          status: ${{ job.status }}
          text: "A new commit was pushed to the main branch:\n\nCommit message: ${{
            github.event.head_commit.message }}\nCommit URL: ${{ github.event.head_commit.url }}\nAuthor: ${{ github.event.head_commit.author.name }}"

        env:
          SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'